SELECT GWP.PRODUCT_NAME, DATE(GWO.DATE_CREATED) AS DATE_CREATED, COUNT(distinct GWOM.ID) AS TOTAL_SUM
FROM GATE_WAYZ_ORDER GWO
INNER JOIN GATE_WAYZ_LEAD GWL ON GWL.ID = GWO.GATE_WAYZ_LEAD_ID
INNER JOIN GATE_WAYZ_PRODUCT GWP ON GWP.ID = GWO.GATE_WAYZ_PRODUCT_ID
INNER JOIN GATE_WAYZ_ORDER_MEMBER GWOM ON GWOM.GATE_WAYZ_ORDER_ID = GWO.ID
INNER JOIN GATE_WAYZ_USER_TEAM GWUT ON GWUT.USER_ID = GWO.CREATED_BY_ID
INNER JOIN GATE_WAYZ_TEAM GWT ON GWT.ID = GWUT.TEAM_ID
WHERE EXTRACT(YEAR FROM GWO.DATE_CREATED) = 2023 AND EXTRACT(MONTH FROM GWO.DATE_CREATED) = 12
AND GWL.LEAD_STATUS IN (2,3,5)  AND GWUT.TEAM_ID IN (104) GROUP BY GWP.PRODUCT_NAME, DATE(GWO.DATE_CREATED)
